# Example game client for libmc--c
#    MinGW makefile

BIN         = mc--c.exe
SRCFILES    = UserInterface.cpp main.cpp
LIBS        = -lmc--c -lopengl32 -lglu32 -lDevIL -lILU \
-lsfml-system -lsfml-window -lsfml-graphics -lz


INCLUDES    = -I/usr/local/include
###DEBUG       = on
MOREFLAGS   = -std=c++0x


#Where to install or uninstall
INSTALL_BIN = $(HOME)/bin

#Generic MinGW build rules for a binary
include bin.MinGW.mak
